Calculator
marioalej/onboarding-kotlin pull request #1
Opened 2018-08-14 13:01 UTC by marioalej

Improved calculator

2018-08-16 13:08 UTC, gaston-mira-glb requested changes

2018-08-16 13:08 UTC, gaston-mira-glb commented on app/src/test/java/com/globant/mariorangel/kotlinonboarding/mvp/presenter/CountPresenterTest.kt
> +        //Mockito.`when`(model.addition("10", ))
don't keep commented code please.

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/model/CountModel.kt
> +import com.globant.mariorangel.kotlinonboarding.mvp.view.CountView
remove this pls

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +    companion object {
move this into model

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +            if (!activity.count_input.text.isEmpty())
move this condition to presenter

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +            if (!activity.count_input.text.isEmpty())
the same

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +            if (!activity.count_input.text.isEmpty())
the same

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +            if (!activity.count_input.text.isEmpty())
the same

2018-08-23 19:11 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +            if (!activity.count_input.text.isEmpty())
the same

2018-08-27 13:33 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/presenter/CountPresenter.kt
> +    fun checkEmptyText() {
Remove if you dont use pls

2018-08-27 13:34 UTC, nacho-globant commented on app/src/main/java/com/globant/mariorangel/kotlinonboarding/mvp/view/CountView.kt
> +import com.globant.mariorangel.kotlinonboarding.mvp.model.CountModel
The view should not know the model.

Move the constant to another class/interface

2018-09-21 14:02 UTC, merged